name: first_action
on: [push]
jobs:
    train-model:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: set up python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        - name: Install dependencies
          run: python -m pip install -r requirements.txt
        - name: Train model
          run: python train.py
        - name: Predict model
          run: python predict.py
        - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with:
            name: classifier_decision_tree.pkl
            path: classifier_decision_tree.pkl